version: '3'

services:
  jenkins:
    image: marmar37/cpp #moj-obraz-jenkinsa  # Ustaw nazwę twojego zbudowanego obrazu Jenkinsa
    container_name: jenkins-new
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Dostęp do Docker socket
    environment:
      - JAVA_OPTS=-Duser.home=/var/jenkins_home
    networks:
      - jenkins_net
    privileged: true  # Umożliwia dostęp do uprawnień roota w kontenerze

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
    networks:
      - jenkins_net
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:alpine
    container_name: sonarqube-db
    networks:
      - jenkins_net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

networks:
  jenkins_net:
    driver: bridge

volumes:
  jenkins_home:
