version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-new
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
    networks:
      - jenkins_net

  sonarqube-db:
    image: postgres:alpine
    container_name: sonarqube-db
    networks:
      - jenkins_net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

networks:
  jenkins_net:
    driver: bridge

volumes:
  jenkins_home:
